### ISSUE TITLE
Release with ssl support forces an update to pubsub 2.0

### ISSUE THREAD

**Issue by JerzyDziala** [phoenixframework/phoenix_pubsub_redis#45]
Hi

We needed to switch to TLS in our redis usage but unfortunately phoenix_pubsub_redis only started supporting ssl a few commits after updating its dependency (phoenix_pubsub) to v2.0.

Sadly the phoenix_pubsub update is a breaking change. We solved this issue by using our fork of phoenix_pubsub_redis which includes support for ssl without changing any dependencies. While this workaround works for us we feel that the elixir community would benefit from having an official hex release with version similar or identical to ours.

Would you consider making a hex release based on this version?
It's literally a one line change in the code but it could provide a lot of value to us and to other developers.
https://github.com/surgeventures/phoenix_pubsub_redis/tree/v2.1.7-redix-config

**Comment by nietaki** [comment]
Here's the diff of changes since the 2.1.7 release: 
https://github.com/phoenixframework/phoenix_pubsub_redis/compare/v2.1.7...surgeventures:v2.1.7-redix-config

It should probably be safe to be released as 2.1.8 while you guys work on the bigger release.

Should solve https://github.com/phoenixframework/phoenix_pubsub_redis/issues/42 too

**Comment by mitchellhenke** [comment]
Thanks for bringing this up! I've merged the changes in #46 and will release 2.1.8 shortly

**Comment by JerzyDziala** [comment]
thanks :)
